In [1]:
# INITIAL SETUP

# Import necessary libraries
import pandas as pd
import numpy as np
import re
import ast
from pathlib import Path



# PATHS, CONSTANTS & VARIABLES

# Set path to datasets
DATA_DIR = Path("~/code/StellaRodriguesLallement/OSE_Project/Dataset_visualization/src/ose_core/data_ingestion/extracted_datasets").expanduser()

In [2]:
# DATA LOADING

df_signals   = pd.read_csv(DATA_DIR / '08_signals.csv', dtype={'siren': str})

In [3]:
df_signals.shape

(2133, 12)

In [7]:
df = df_signals.copy()

# Convert the 'type' JSON-like string into a dictionary
df['type'] = df['type'].apply(ast.literal_eval)

# Extract fields
df['signal_code'] = df['type'].apply(lambda x: x.get('code'))
df['signal_label'] = df['type'].apply(lambda x: x.get('label'))

df['publishedAt'] = pd.to_datetime(df['publishedAt'], utc=True)

df.columns

Index(['company_name', 'siren', 'siret', 'continent', 'country', 'departement',
       'publishedAt', 'isMain', 'type', 'createdAt', 'companies_count',
       'sirets_count', 'signal_code', 'signal_label'],
      dtype='object')

In [8]:
df.head(3)

,company_name,siren,siret,continent,country,departement,publishedAt,isMain,type,createdAt,companies_count,sirets_count,signal_code,signal_label
0,PAIN D'EPICES MULOT ET PETITJEAN,015751530,1575153000013,"[{'id': 6, 'label': 'Europe'}]","[{'id': 72, 'label': 'France'}]","[{'parent': 'Bourgogne-Franche-Comté', 'id': 2...",2021-09-29 22:00:00+00:00,True,"{'code': 'K1', 'id': 32, 'label': 'Investissem...",2020-09-07T15:14:38+02:00,1,1,K1,Investissements
1,PAIN D'EPICES MULOT ET PETITJEAN,015751530,1575153000013,"[{'id': 6, 'label': 'Europe'}]","[{'id': 72, 'label': 'France'}]","[{'parent': 'Bourgogne-Franche-Comté', 'id': 2...",2020-09-07 22:00:00+00:00,True,"{'code': 'L', 'id': 12, 'label': 'Levée de fon...",2020-09-07T15:14:12+02:00,1,1,L,"Levée de fonds, financements & modifs. capital"
2,PAIN D'EPICES MULOT ET PETITJEAN,015751530,1575153000013,NaN,NaN,NaN,2016-09-20 22:00:00+00:00,True,"{'code': 'F', 'id': 6, 'label': 'Développement...",2016-09-20T10:45:13+02:00,1,1,F,Développement de l'activité

In [10]:
cutoff = pd.Timestamp.now(tz='UTC') - pd.DateOffset(months=12)
df[df['publishedAt'] >= cutoff].copy()

,company_name,siren,siret,continent,country,departement,publishedAt,isMain,type,createdAt,companies_count,sirets_count,signal_code,signal_label
17,PAIN D'EPICES MULOT ET PETITJEAN,015751530,1575153000013,NaN,NaN,"[{'parent': 'Bourgogne-Franche-Comté', 'id': 2...",2025-03-02 23:15:21+00:00,True,"{'code': 'N', 'label_short': 'Recrutement', 'i...",2025-02-28T15:34:14+01:00,1,1,N,Recrutement
35,LAITERIE DE MAYOTTE,099378564,9937856400019,NaN,NaN,"[{'parent': 'DOM-TOM', 'id': 108, 'label': 'Ma...",2025-09-24 22:15:40+00:00,True,"{'code': 'F', 'label_short': 'Croissance', 'id...",2025-09-24T10:35:38+02:00,1,1,F,Développement de l'activité
36,LAITERIE DE MAYOTTE,099378564,9937856400019,NaN,NaN,"[{'parent': 'DOM-TOM', 'id': 108, 'label': 'Ma...",2025-09-24 22:15:40+00:00,True,"{'code': 'K1', 'label_short': 'Investissement'...",2025-09-24T10:34:40+02:00,1,1,K1,Investissements
37,LAITERIE DE MAYOTTE,099378564,9937856400019,NaN,NaN,"[{'parent': 'DOM-TOM', 'id': 108, 'label': 'Ma...",2025-09-24 22:15:40+00:00,True,"{'code': 'S', 'label_short': 'Lancement', 'id'...",2025-09-24T10:35:15+02:00,1,1,S,Lancement
54,SO COP LAITIERE DE HTE MAURIENNE VANOISE,301164620,30116462000017,NaN,NaN,"[{'parent': 'Auvergne-Rhône-Alpes', 'id': 73, ...",2025-10-02 22:15:23+00:00,True,"{'code': 'K1', 'label_short': 'Investissement'...",2025-10-02T16:31:04+02:00,1,1,K1,Investissements
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2091,ETABLISSEMENTS CASTAING ET FILS,896150042,89615004200043,NaN,NaN,"[{'parent': 'Nouvelle Aquitaine', 'id': 40, 'l...",2025-04-29 22:15:13+00:00,True,"{'code': 'L', 'label_short': 'Levée de fonds, ...",2025-04-29T14:00:02+02:00,2,1,L,"Levée de fonds, financements & modifs. capital"
2092,ETABLISSEMENTS CASTAING ET FILS,896150042,89615004200043,NaN,NaN,"[{'parent': 'Nouvelle Aquitaine', 'id': 40, 'l...",2025-04-29 22:15:13+00:00,True,"{'code': 'K1', 'label_short': 'Investissement'...",2025-04-29T13:59:13+02:00,1,1,K1,Investissements
2093,ETABLISSEMENTS CASTAING ET FILS,896150042,89615004200043,NaN,NaN,"[{'parent': 'Nouvelle Aquitaine', 'id': 40, 'l...",2025-04-29 22:15:13+00:00,True,"{'code': 'N', 'label_short': 'Recrutement', 'i...",2025-04-29T13:59:33+02:00,1,1,N,Recrutement
2103,GOURMALLIANCE,901761114,90176111400015,"[{'id': 10, 'label': 'Continent non précisé'}]","[{'id': 253, 'label': 'Pays non précisé'}]","[{'parent': 'Île-de-France', 'id': 95, 'label'...",2025-01-13 23:15:22+00:00,True,"{'code': 'Hbis', 'label_short': 'International...",2025-01-13T11:17:07+01:00,1,1,Hbis,Activité internationale (industrie)
2104,GOURMALLIANCE,901761114,90176111400015,NaN,NaN,"[{'parent': 'Île-de-France', 'id': 95, 'label'...",2025-01-13 23:15:22+00:00,True,"{'code': 'F', 'label_short': 'Croissance', 'id...",2025-01-13T11:16:45+01:00,1,1,F,Développement de l'activité

In [11]:
positive_codes = ['B', 'K1', 'F', 'E', 'S']   # Construction, Investissements, Croissance, Création, Lancement produits
negative_codes = ['M', 'O', 'I']              # Licenciement, RJ/LJ, Fermeture

In [ ]:

df['signal_valence'] = 'neutral'
df.loc[df['signal_code'].isin(positive_codes), 'signal_valence'] = 'positive'
df.loc[df['signal_code'].isin(negative_codes), 'signal_valence'] = 'negative'

In [15]:
df.shape

(2133, 15)

In [16]:
df.head(7)

,company_name,siren,siret,continent,country,departement,publishedAt,isMain,type,createdAt,companies_count,sirets_count,signal_code,signal_label,signal_valence
0,PAIN D'EPICES MULOT ET PETITJEAN,015751530,1575153000013,"[{'id': 6, 'label': 'Europe'}]","[{'id': 72, 'label': 'France'}]","[{'parent': 'Bourgogne-Franche-Comté', 'id': 2...",2021-09-29 22:00:00+00:00,True,"{'code': 'K1', 'id': 32, 'label': 'Investissem...",2020-09-07T15:14:38+02:00,1,1,K1,Investissements,positive
1,PAIN D'EPICES MULOT ET PETITJEAN,015751530,1575153000013,"[{'id': 6, 'label': 'Europe'}]","[{'id': 72, 'label': 'France'}]","[{'parent': 'Bourgogne-Franche-Comté', 'id': 2...",2020-09-07 22:00:00+00:00,True,"{'code': 'L', 'id': 12, 'label': 'Levée de fon...",2020-09-07T15:14:12+02:00,1,1,L,"Levée de fonds, financements & modifs. capital",neutral
2,PAIN D'EPICES MULOT ET PETITJEAN,015751530,1575153000013,NaN,NaN,NaN,2016-09-20 22:00:00+00:00,True,"{'code': 'F', 'id': 6, 'label': 'Développement...",2016-09-20T10:45:13+02:00,1,1,F,Développement de l'activité,positive
3,PAIN D'EPICES MULOT ET PETITJEAN,015751530,1575153000013,"[{'id': 1, 'label': 'Asie'}]",NaN,NaN,2018-04-05 22:00:00+00:00,True,"{'code': 'F', 'id': 6, 'label': 'Développement...",2018-04-05T11:16:18+02:00,1,1,F,Développement de l'activité,positive
4,PAIN D'EPICES MULOT ET PETITJEAN,015751530,1575153000013,"[{'id': 1, 'label': 'Asie'}]",NaN,NaN,2018-04-05 22:00:00+00:00,True,"{'code': 'E', 'id': 5, 'label': 'Créations & o...",2018-04-05T11:15:32+02:00,1,1,E,Créations & ouvertures,positive
5,PAIN D'EPICES MULOT ET PETITJEAN,015751530,1575153000013,"[{'id': 1, 'label': 'Asie'}]",NaN,NaN,2018-04-05 22:00:00+00:00,True,"{'code': 'H', 'id': 8, 'label': 'Activité inte...",2018-04-05T11:14:31+02:00,1,1,H,Activité internationale (tertiaire),neutral
6,PAIN D'EPICES MULOT ET PETITJEAN,015751530,1575153000013,NaN,NaN,NaN,2014-05-19 22:00:00+00:00,True,"{'code': 'X', 'id': 25, 'label': 'Actualité en...",2014-05-16T10:10:24+02:00,1,1,X,Actualité entreprise,neutral

In [18]:
valence = (df.groupby(['siren', 'signal_valence'])
        .size()
        .unstack(fill_value=0)
        .rename(columns={
            'positive': 'n_positive_signals',
            'negative': 'n_negative_signals',
            'neutral':  'n_neutral_signals'
        })
    )

In [19]:
valence.shape

(266, 3)

In [20]:
valence.head(15)

signal_valence  n_negative_signals  n_neutral_signals  n_positive_signals
siren
015751530                        0                  9                  11
046580031                        0                  2                   3
057504649                        0                  0                   2
086781150                        0                  0                   2
096780838                        0                  5                   1
099378564                        0                  0                   3
300700119                        0                  1                   1
300882131                        0                  7                   7
301164620                        0                  1                   1
301710349                        0                  0                   1
304915432                        0                  8                   0
306979519                        0                  2                   4
307107037                        0                  4                   1
308065499                        0                  3                   2
310336938                        0                  0                   1

In [22]:
# Code summary
code_counts = (
    df.groupby(['siren', 'signal_code'])
    .size()
    .unstack(fill_value=0)
    .add_prefix('n_code_')
)

In [23]:
code_counts.shape

(266, 25)

In [24]:
code_counts.head(7)

signal_code,n_code_A,n_code_B,n_code_D,n_code_E,n_code_F,n_code_G,n_code_H,n_code_Hbis,n_code_I,n_code_K1,...,n_code_R,n_code_S,n_code_U,n_code_W,n_code_X,n_code_Y,n_code_Z,n_code_Z1,n_code_Z2,n_code_Z3
siren,,,,,,,,,,,,,,,,,,,,,
015751530,0,3,0,1,3,0,3,1,0,3,...,0,1,1,0,1,0,0,0,0,0
046580031,0,2,0,0,0,0,0,0,0,1,...,0,0,0,0,0,0,0,0,0,0
057504649,0,1,0,0,0,0,0,0,0,1,...,0,0,0,0,0,0,0,0,0,0
086781150,0,2,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
096780838,0,0,0,0,0,0,0,0,0,1,...,0,0,0,0,0,0,0,1,1,0
099378564,0,0,0,0,1,0,0,0,0,1,...,0,1,0,0,0,0,0,0,0,0
300700119,0,0,0,0,0,0,0,0,0,1,...,0,0,0,0,0,0,0,0,0,0

In [25]:
valence.join(code_counts, how='outer').fillna(0)

,n_negative_signals,n_neutral_signals,n_positive_signals,n_code_A,n_code_B,n_code_D,n_code_E,n_code_F,n_code_G,n_code_H,...,n_code_R,n_code_S,n_code_U,n_code_W,n_code_X,n_code_Y,n_code_Z,n_code_Z1,n_code_Z2,n_code_Z3
siren,,,,,,,,,,,,,,,,,,,,,
015751530,0,9,11,0,3,0,1,3,0,3,...,0,1,1,0,1,0,0,0,0,0
046580031,0,2,3,0,2,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
057504649,0,0,2,0,1,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
086781150,0,0,2,0,2,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
096780838,0,5,1,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,1,1,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
901761114,0,1,1,0,0,0,0,1,0,0,...,0,0,0,0,0,0,0,0,0,0
916420128,0,3,7,0,1,0,0,0,0,0,...,1,1,0,0,0,0,0,0,0,0
927050013,0,0,3,0,3,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
947351656,0,7,2,0,0,0,0,1,0,1,...,0,0,0,0,0,0,0,0,0,0
950451518,0,3,3,0,3,0,0,0,0,1,...,0,0,0,0,0,0,0,0,0,0